version: '3.8'

services:
  patient-service:
    build: ./patient-service
    ports:
      - "8001:8000"
    depends_on:
      - db

  doctor-service:
    build: ./doctor-service
    ports:
      - "8002:8000"
    depends_on:
      - db

  appointment-service:
    build: ./appointment-service
    ports:
      - "8003:8000"
    depends_on:
      - db
      - rabbitmq

  notification-service:
    build: ./notification-service
    ports:
      - "8004:8000"
    depends_on:
      - rabbitmq

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
